import { motion } from "framer-motion";
import {
  Shield,
  Linkedin,
  ExternalLink,
  Brain,
  Waves,
  Fingerprint,
  Code,
  Award,
} from "lucide-react";

const fadeInUp = {
  hidden: { opacity: 0, y: 30 },
  visible: { opacity: 1, y: 0 },
};

const staggerContainer = {
  hidden: { opacity: 0 },
  visible: {
    opacity: 1,
    transition: {
      staggerChildren: 0.15,
    },
  },
};

const teamMembers = [
  {
    name: "Shailav Malik",
    role: "Team Lead & ML Engineer",
    linkedin: "https://linkedin.com/in/shailavmalik",
    gradient: "from-neon-cyan to-neon-blue",
    image: "/img/shailav.png",
  },
  {
    name: "Ritika Sharma",
    role: "Frontend Developer",
    linkedin: "https://www.linkedin.com/in/ritika-sharma-012979398/",
    gradient: "from-neon-purple to-neon-pink",
    image: "/img/ritika.png",
  },
  {
    name: "Sarthak Vats",
    role: "Architecture Design",
    linkedin: "https://www.linkedin.com/in/sarthak-vats-301a3a358/",
    gradient: "from-neon-cyan to-neon-purple",
    image: "/img/sarthak.png",
  },
  {
    name: "Tarun Kumar",
    role: "ML & Data Engineer",
    linkedin: "https://www.linkedin.com/in/tarun-kumar-7238b1367/",
    gradient: "from-neon-pink to-neon-cyan",
    image: "/img/tarun.png",
  },
];

const features = [
  {
    icon: Brain,
    title: "Neural Network Analysis",
    description:
      "ResNet-style architecture with Wav2Vec2 embeddings for deep audio understanding.",
  },
  {
    icon: Waves,
    title: "798 Acoustic Features",
    description:
      "MFCCs, pitch analysis, spectral features, and deep speech representations.",
  },
  {
    icon: Fingerprint,
    title: "Voice Forensics",
    description:
      "Detects subtle artifacts unique to AI-generated speech like pitch jitter and smoothness.",
  },
  {
    icon: Code,
    title: "Production Ready",
    description:
      "FastAPI backend with async processing, deployed on scalable cloud infrastructure.",
  },
];

export default function AboutPage() {
  return (
    <div className="max-w-6xl mx-auto px-4 py-8">
      <motion.div
        initial="hidden"
        animate="visible"
        variants={staggerContainer}>
        {/* Header */}
        <motion.div variants={fadeInUp} className="text-center mb-16">
          <motion.div
            initial={{ scale: 0 }}
            animate={{ scale: 1 }}
            transition={{ type: "spring", stiffness: 200 }}
            className="inline-flex p-4 rounded-2xl bg-neon-cyan/10 mb-6">
            <Shield className="w-12 h-12 text-neon-cyan" />
          </motion.div>
          <h1 className="text-4xl md:text-5xl font-bold mb-4">
            About <span className="neon-text">VoxProof</span>
          </h1>
          <p className="text-lg text-dark-500 dark:text-light-400 max-w-2xl mx-auto">
            An advanced AI voice forensics system designed to combat audio fraud
            and deepfake technology.
          </p>
        </motion.div>

        {/* Project Info */}
        <motion.div variants={fadeInUp} className="mb-16">
          <div className="glass-card p-8 md:p-12">
            <div className="flex flex-col md:flex-row items-center gap-8">
              <div className="flex-1">
                <div className="flex items-center gap-2 mb-4">
                  <Award className="w-5 h-5 text-neon-cyan" />
                  <span className="text-sm font-medium text-neon-cyan">
                    AI Impact Buildathon 2026
                  </span>
                </div>
                <h2 className="text-2xl md:text-3xl font-bold mb-4">
                  Detecting AI Voices with AI
                </h2>
                <p className="text-dark-500 dark:text-light-400 mb-6">
                  VoxProof is a production-ready AI voice detection platform
                  that analyzes audio recordings to determine whether they were
                  produced by a human or generated by AI systems like
                  ElevenLabs, OpenAI, or Coqui TTS.
                </p>
                <p className="text-dark-500 dark:text-light-400">
                  Our system extracts 798 acoustic features from audio samples
                  and uses a ResNet-style neural network with Wav2Vec2
                  embeddings to achieve high-accuracy classification with
                  detailed explanations.
                </p>
              </div>
              <div className="w-full md:w-auto">
                <div className="grid grid-cols-2 gap-4">
                  <StatCard label="Features" value="798" />
                  <StatCard label="Accuracy" value="95%+" />
                  <StatCard label="Languages" value="5" />
                  <StatCard label="Latency" value="<8s" />
                </div>
              </div>
            </div>
          </div>
        </motion.div>

        {/* Technical Features */}
        <motion.div variants={fadeInUp} className="mb-16">
          <h2 className="text-2xl md:text-3xl font-bold text-center mb-12">
            Technical <span className="neon-text">Features</span>
          </h2>
          <div className="grid md:grid-cols-2 gap-6">
            {features.map((feature) => (
              <motion.div
                key={feature.title}
                variants={fadeInUp}
                whileHover={{ scale: 1.02 }}
                className="glass-card-hover p-6 flex gap-4">
                <div className="flex-shrink-0 p-3 rounded-xl bg-neon-cyan/10">
                  <feature.icon className="w-6 h-6 text-neon-cyan" />
                </div>
                <div>
                  <h3 className="font-semibold mb-2">{feature.title}</h3>
                  <p className="text-sm text-dark-500 dark:text-light-400">
                    {feature.description}
                  </p>
                </div>
              </motion.div>
            ))}
          </div>
        </motion.div>

        {/* Team Section */}
        <motion.div variants={fadeInUp}>
          <div className="text-center mb-12">
            <h2 className="text-2xl md:text-3xl font-bold mb-4">
              Meet <span className="neon-text">Meerut Coders</span>
            </h2>
            <p className="text-dark-500 dark:text-light-400">
              The talented team behind VoxProof
            </p>
          </div>

          <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {teamMembers.map((member) => (
              <motion.div
                key={member.name}
                variants={fadeInUp}
                whileHover={{ y: -5 }}
                className="glass-card-hover p-6 text-center group">
                {/* Avatar with Image */}
                <div className="relative mb-6">
                  <div
                    className={`
                      relative w-24 h-24 mx-auto rounded-full overflow-hidden
                      ring-2 ring-transparent group-hover:ring-neon-cyan/50
                      shadow-lg group-hover:shadow-neon-glow transition-all duration-300
                    `}>
                    {/* Gradient border effect */}
                    <div
                      className={`absolute -inset-0.5 bg-gradient-to-br ${member.gradient} rounded-full opacity-0 group-hover:opacity-100 transition-opacity blur-sm`}
                    />
                    <img
                      src={member.image}
                      alt={member.name}
                      className="relative w-full h-full object-cover rounded-full"
                      onError={(e) => {
                        // Fallback to initials if image fails to load
                        const target = e.target as HTMLImageElement;
                        target.style.display = "none";
                        const parent = target.parentElement;
                        if (parent) {
                          parent.innerHTML = `<div class="w-full h-full flex items-center justify-center text-2xl font-bold text-white bg-gradient-to-br ${member.gradient}">${member.name
                            .split(" ")
                            .map((n) => n[0])
                            .join("")}</div>`;
                        }
                      }}
                    />
                  </div>
                  <motion.div
                    className={`
                      absolute inset-0 rounded-full bg-gradient-to-br ${member.gradient}
                      blur-xl opacity-0 group-hover:opacity-30 transition-opacity
                    `}
                  />
                </div>

                {/* Info */}
                <h3 className="font-semibold text-lg mb-1">{member.name}</h3>
                <p className="text-sm text-dark-500 dark:text-light-400 mb-4">
                  {member.role}
                </p>

                {/* LinkedIn Link */}
                <a
                  href={member.linkedin}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-[#0077B5]/10 text-[#0077B5] hover:bg-[#0077B5]/20 transition-colors text-sm">
                  <Linkedin className="w-4 h-4" />
                  LinkedIn
                  <ExternalLink className="w-3 h-3" />
                </a>
              </motion.div>
            ))}
          </div>
        </motion.div>

        {/* Tech Stack */}
        <motion.div variants={fadeInUp} className="mt-16">
          <div className="glass-card p-8">
            <h3 className="text-xl font-semibold mb-6 text-center">
              Built With
            </h3>
            <div className="flex flex-wrap justify-center gap-4">
              {[
                "React",
                "Vite",
                "FastAPI",
                "PyTorch",
                "Wav2Vec2",
                "Tailwind CSS",
                "Framer Motion",
                "Python",
              ].map((tech) => (
                <span
                  key={tech}
                  className="px-4 py-2 rounded-full bg-dark-800 dark:bg-neon-cyan/10 text-neon-cyan text-sm font-medium border border-neon-cyan/30 shadow-sm">
                  {tech}
                </span>
              ))}
            </div>
          </div>
        </motion.div>
      </motion.div>
    </div>
  );
}

function StatCard({ label, value }: { label: string; value: string }) {
  return (
    <div className="p-4 rounded-xl bg-white/50 dark:bg-dark-700/50 text-center">
      <p className="text-2xl font-bold neon-text">{value}</p>
      <p className="text-xs text-dark-500 dark:text-light-400">{label}</p>
    </div>
  );
}
